# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{widgets}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin MacKenzie IV"]
  s.date = %q{2011-02-09}
  s.description = %q{widget, n : a device that is very useful for a particular job

Widgets make it easier for a developer to add internal domain-specific languages (DSLs) to
their application while keeping the DSL code separate from the objects it manipulates.}
  s.email = %q{sinisterchipmunk@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/widget.rb",
    "lib/widget/class_methods.rb",
    "lib/widget/proxy_module.rb",
    "lib/widgets.rb",
    "lib/widgets/class_methods.rb",
    "lib/widgets/configuration.rb",
    "lib/widgets/errors.rb",
    "lib/widgets/proxy_set.rb",
    "lib/widgets/railtie.rb",
    "lib/widgets/stderr_logger.rb",
    "spec/behaviors/widget_entry_points_spec.rb",
    "spec/behaviors/widget_subprocessing_spec.rb",
    "spec/lib/widget_spec.rb",
    "spec/lib/widgets/configuration_spec.rb",
    "spec/lib/widgets/stderr_logger_spec.rb",
    "spec/lib/widgets_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/ancestry_matcher.rb",
    "spec/support/custom_matchers.rb",
    "spec/support/mock_widgets.rb",
    "spec/widgets/test_widget.rb",
    "widgets.gemspec"
  ]
  s.homepage = %q{http://github.com/sinisterchipmunk/widgets}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{widget, n : a device that is very useful for a particular job}
  s.test_files = [
    "spec/behaviors/widget_entry_points_spec.rb",
    "spec/behaviors/widget_subprocessing_spec.rb",
    "spec/lib/widget_spec.rb",
    "spec/lib/widgets/configuration_spec.rb",
    "spec/lib/widgets/stderr_logger_spec.rb",
    "spec/lib/widgets_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/ancestry_matcher.rb",
    "spec/support/custom_matchers.rb",
    "spec/support/mock_widgets.rb",
    "spec/widgets/test_widget.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

